### ISSUE TITLE
Missing support for password protected archives

### ISSUE THREAD

**Issue by Vadiml1024** [smartfile/python-libarchive#16]
It is pretty trivial to add, whould you accept a patch?

**Comment by cabarnes** [comment]
Please open a PR and I will review it. Thanks!

**Comment by Vadiml1024** [comment]
I've based my fork on https://github.com/richnetdesign/python-libarchive...
Si i'm not sure i'm able to create pull request here....

**Comment by Vadiml1024** [comment]
Ok found how to do it...
https://github.com/smartfile/python-libarchive/pull/17

**Comment by Vadiml1024** [comment]
Fixed by https://github.com/smartfile/python-libarchive/pull/17
