### ISSUE TITLE
Package information out of date

### ISSUE THREAD

**Issue by mxmlnkn** [smartfile/python-libarchive#20]
- The download URL still points to python-libarchive.googlecode.de
 - The mail now points to vadim1024. I tried the previous one and it was disfunctional, so, I guess it's a bit better but this was probably changed thinking a fork might be necessary.
 - A `__version__` member might be helpful to me especially as the package name is different from the module name but I might not be mainstream with my dislike of `importlib.metadata.version`.

Steps to reproduce:

```python3
import importlib.metadata
print(dict(importlib.metadata.distribution("python-libarchive").metadata))
```

**Comment by cabarnes** [comment]
When I do those steps, I see version `4.1.1` which is correct
```
>>> print(dict(importlib.metadata.distribution("python-libarchive").metadata))
{'Metadata-Version': '2.1', 'Name': 'python-libarchive', 'Version': '4.1.1',
```
Are you getting a different result?

**Comment by mxmlnkn** [comment]
I'm also getting 4.1.1. But, I think the `Download-URL` (`http://python-libarchive.googlecode.com/files/python-libarchive-4.1.1.tar.gz`) and `Author-email` are not correct.
