### ISSUE TITLE
Failed to download on mac-x64 with python 3.11.5

### ISSUE THREAD

**Issue by zchrissirhcz** [smartfile/python-libarchive#39]
```
(base) ➜  zip git:(main) ✗ pip install python-libarchive
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting python-libarchive
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/47/2f/4dc8be4fa6f835786c359b918d131ab748727446336e9030ad5b41603740/python-libarchive-4.2.1.tar.gz (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.5/58.5 kB 24.3 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: python-libarchive
  Building wheel for python-libarchive (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-x86_64-cpython-311
      creating build/lib.macosx-10.9-x86_64-cpython-311/libarchive
      copying libarchive/tar.py -> build/lib.macosx-10.9-x86_64-cpython-311/libarchive
      copying libarchive/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-311/libarchive
      copying libarchive/_libarchive.py -> build/lib.macosx-10.9-x86_64-cpython-311/libarchive
      copying libarchive/zip.py -> build/lib.macosx-10.9-x86_64-cpython-311/libarchive
      running build_ext
      building 'libarchive.__libarchive' extension
      creating build/temp.macosx-10.9-x86_64-cpython-311
      creating build/temp.macosx-10.9-x86_64-cpython-311/libarchive
      clang -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/chris/soft/miniconda3/include -fPIC -O2 -isystem /Users/chris/soft/miniconda3/include -I/usr/local/include -Ilibarchive -I/Users/chris/soft/miniconda3/include/python3.11 -c libarchive/_libarchive_wrap.c -o build/temp.macosx-10.9-x86_64-cpython-311/libarchive/_libarchive_wrap.o
      libarchive/_libarchive_wrap.c:2712:10: fatal error: 'archive.h' file not found
      #include <archive.h>
               ^~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for python-libarchive
  Running setup.py clean for python-libarchive
Failed to build python-libarchive
ERROR: Could not build wheels for python-libarchive, which is required to install pyproject.toml-based projects
```

**Comment by ghost** [comment]
Hi @zchrissirhcz, I encountered the exact same problem with you.

A [Stackoverflow post](https://stackoverflow.com/questions/61799988/how-to-install-libarchive-on-macos-and-make-compiler-will-detect-it) points out that `libarchive` installed by `brew` is not in the standard system paths.

The workaround that I have made is to export the `libarchive` headers to `C_INCLUDE_PATH`, so that `archive.h` can be discovered by `clang`:

```zsh
export C_INCLUDE_PATH="/usr/local/opt/libarchive/include"
```

Hope this helps!

**Comment by zchrissirhcz** [comment]
> Hi @zchrissirhcz, I encountered the exact same problem with you.
> 
> A [Stackoverflow post](https://stackoverflow.com/questions/61799988/how-to-install-libarchive-on-macos-and-make-compiler-will-detect-it) points out that `libarchive` installed by `brew` is not in the standard system paths.
> 
> The workaround that I have made is to export the `libarchive` headers to `C_INCLUDE_PATH`, so that `archive.h` can be discovered by `clang`:
> 
> ```shell
> export C_INCLUDE_PATH="/usr/local/opt/libarchive/include"
> ```
> 
> Hope this helps!

Thanks for the tips. I'll try it when I have my mac-x64 an hand.

Actually I was finding a python library which can decompress `.a` / `.lib` (static library) files, and Python standard library `zipfile` is enough for me to unzip `.zip` files.

For my requirement, an `7z` / `7zx` of 7-zip's Python wrapper is the ultimate choice, but I did not find. And finally I find https://github.com/vidstige/ar , adapted it with BSD/Windows variants in my own fork.
